### PR TITLE
#201 fix terms and handling of terms with commas

### PR DESCRIPTION
**Pull request by xadxura**
Updated terms to standardize mediums with lower case and other minor changes. Added new terms for missing terms and updated for Mayan terms. Fixed bug in Entity to handle comma'd terms.

### CODE REVIEW

**Comment by stevewh** [comment]
The term.sql conflicts with trm_id values in use for Mayan. enclosed is a term.sql (marked as term.txt) that should be ok with the exception of the location property labels (country, district, area, site, etc.) and numbering style in any database that uses these trm_ids. This can be done through checking trm_id fields in the datamodel for the old id values and updating them to the new values. We should review this to identify which databases require change.
[term.txt](https://github.com/readsoftware/read/files/7111856/term.txt)

for the regular expression we should test a string of labels like  'en=>"schist, green", it=>"scisto, verde"'

**Comment by xadxura** [comment]
> The term.sql conflicts with trm_id values in use for Mayan. enclosed is a term.sql (marked as term.txt) that should be ok with the exception of the location property labels (country, district, area, site, etc.) and numbering style in any database that uses these trm_ids. This can be done through checking trm_id fields in the datamodel for the old id values and updating them to the new values. We should review this to identify which databases require change.
> [term.txt](https://github.com/readsoftware/read/files/7111856/term.txt)
> 
> for the regular expression we should test a string of labels like 'en=>"schist, green", it=>"scisto, verde"'

Pushed and updated term list which retains the IDs for Mayan. The IDs are now off for Gandhari, but we have no expectation or need to take an update to Gandhari.orgs db from terms.sql, so the differences can be ignored.
I tested 'en=>"schist, green", it=>"scisto, verde"' and found that the updated code works as intended for en - value returned is schist, green, not scisto, verde. Result is better than previous form for this string. I didn't try changing the language code to try and extract the Italian string.

**Comment by xadxura** [comment]
@stevewh, this should be ready to merge.

**Comment by stevewh** [comment]
Great work!   We should create an issue for the testing of multiple
language term extraction with low priority.

**Pull request merged**
