### PR TITLE
Put SketchFab and D3 into config

### PR DESCRIPTION
**Pull request by xadxura**
Put Sketchfab and D3 behind a config constant

### CODE REVIEW

**Review by stevewh — CHANGES_REQUESTED** [review]
USE_D3 makes more sense as the library is d3.js

**Review by stevewh — COMMENTED** [review]
<?php
    if (USE_SKETCHFAB) {
      echo '<script type=\"text/javascript\" src=\"/sketchfab/sketchfab-viewer-1.8.2.js\"></script>';
    }
    if (USE_D3PATH) {
      echo '<script src=\"/d3/d3.js\"></script>';
    }
    ?>

Another common way to write this code without extra functions is:
<?php
    if (USE_SKETCHFAB) {
?>
      <script type=\"text/javascript\" src=\"/sketchfab/sketchfab-viewer-1.8.2.js\"></script>
<?php
    }
    if (USE_D3PATH) {
?>
      <script src=\"/d3/d3.js\"></script>
<?php
    }
 ?>

**Comment by xadxura** [comment]
> USE_D3 makes more sense as the library is d3.js

Fixed.

**Comment by xadxura** [comment]
> </script>'; } if (USE_D3PATH) { echo '<script src=\"/d3/d3.js\"></script>'; } ?>
> Another common way to write this code without extra functions is:
> 
> ```
>   <script type=\"text/javascript\" src=\"/sketchfab/sketchfab-viewer-1.8.2.js\"></script>
> ```
> 
> ```
>   <script src=\"/d3/d3.js\"></script>
> ```

Without the echo statement? As in, drop out of  PHP backto HTML? Personally, I like to stick within the same language, but happy to adapt if that's the style.

**Review by stevewh — APPROVED** [review]

**Pull request merged**
